on: [push]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - run: docker build . -t ${{ github.repository }}:${{ github.sha }}
      
    - uses: Azure/container-scan@v0
      with:
        image-name: ${{ github.repository }}:${{ github.sha }}
